INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5000, 'Harry Potter', 'Livros', 'Livro do genero fantasia', 10)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5001, '1984', 'Livros', '', 7)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5002, 'Notebook', 'Eletronicos', '', 15)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5003, 'TV', 'Eletronicos', '', 3)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5004, 'Admiravel mundo novo', 'Livros', 'Livro do genero romance', 10)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5005, 'Don Quixote', 'Livros', 'Livro do genero aventura', 2)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5006, 'Violino', 'Instrumentos Musicais', '', 12)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5007, 'Acordeon', 'Instrumentos Musicais', '', 7)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5008, 'Escrivaninha', 'Mobilia', 'Escrivaninha L:140cm x W:60cm x H:70cm', 4)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5009, 'Flauta Doce', 'Instrumentos Musicais', '', 1)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5010, 'O Mundo de Sofia', 'Livros', '', 4)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5011, 'Teclado', 'Eletronicos', 'Teclado para computador', 9)
INSERT INTO produto (id, nome, categoria, descricao, quantidade) values (5012, 'Teclado', 'Instrumentos Musicais', '', 14)